// Generated by gencpp from file test3/turtleSrvResponse.msg
// DO NOT EDIT!


#ifndef TEST3_MESSAGE_TURTLESRVRESPONSE_H
#define TEST3_MESSAGE_TURTLESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test3
{
template <class ContainerAllocator>
struct turtleSrvResponse_
{
  typedef turtleSrvResponse_<ContainerAllocator> Type;

  turtleSrvResponse_()
    : result()  {
    }
  turtleSrvResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::test3::turtleSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test3::turtleSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct turtleSrvResponse_

typedef ::test3::turtleSrvResponse_<std::allocator<void> > turtleSrvResponse;

typedef boost::shared_ptr< ::test3::turtleSrvResponse > turtleSrvResponsePtr;
typedef boost::shared_ptr< ::test3::turtleSrvResponse const> turtleSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test3::turtleSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test3::turtleSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test3::turtleSrvResponse_<ContainerAllocator1> & lhs, const ::test3::turtleSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test3::turtleSrvResponse_<ContainerAllocator1> & lhs, const ::test3::turtleSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test3::turtleSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test3::turtleSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test3::turtleSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test3::turtleSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test3::turtleSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test3::turtleSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test3::turtleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::test3::turtleSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::test3::turtleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test3/turtleSrvResponse";
  }

  static const char* value(const ::test3::turtleSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test3::turtleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::test3::turtleSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test3::turtleSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtleSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test3::turtleSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test3::turtleSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST3_MESSAGE_TURTLESRVRESPONSE_H
