// Generated by gencpp from file test3/turtleSrvRequest.msg
// DO NOT EDIT!


#ifndef TEST3_MESSAGE_TURTLESRVREQUEST_H
#define TEST3_MESSAGE_TURTLESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test3
{
template <class ContainerAllocator>
struct turtleSrvRequest_
{
  typedef turtleSrvRequest_<ContainerAllocator> Type;

  turtleSrvRequest_()
    : name()
    , v(0.0)
    , omega(0.0)
    , move(false)  {
    }
  turtleSrvRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , v(0.0)
    , omega(0.0)
    , move(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _v_type;
  _v_type v;

   typedef double _omega_type;
  _omega_type omega;

   typedef uint8_t _move_type;
  _move_type move;





  typedef boost::shared_ptr< ::test3::turtleSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test3::turtleSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct turtleSrvRequest_

typedef ::test3::turtleSrvRequest_<std::allocator<void> > turtleSrvRequest;

typedef boost::shared_ptr< ::test3::turtleSrvRequest > turtleSrvRequestPtr;
typedef boost::shared_ptr< ::test3::turtleSrvRequest const> turtleSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test3::turtleSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test3::turtleSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test3::turtleSrvRequest_<ContainerAllocator1> & lhs, const ::test3::turtleSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.v == rhs.v &&
    lhs.omega == rhs.omega &&
    lhs.move == rhs.move;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test3::turtleSrvRequest_<ContainerAllocator1> & lhs, const ::test3::turtleSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test3::turtleSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test3::turtleSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test3::turtleSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test3::turtleSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test3::turtleSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test3::turtleSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test3::turtleSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae8d4dd14ded1dd1b4bfd0334603122a";
  }

  static const char* value(const ::test3::turtleSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae8d4dd14ded1dd1ULL;
  static const uint64_t static_value2 = 0xb4bfd0334603122aULL;
};

template<class ContainerAllocator>
struct DataType< ::test3::turtleSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test3/turtleSrvRequest";
  }

  static const char* value(const ::test3::turtleSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test3::turtleSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64  v\n"
"float64  omega\n"
"bool   move\n"
"\n"
;
  }

  static const char* value(const ::test3::turtleSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test3::turtleSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.v);
      stream.next(m.omega);
      stream.next(m.move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtleSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test3::turtleSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test3::turtleSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "omega: ";
    Printer<double>::stream(s, indent + "  ", v.omega);
    s << indent << "move: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST3_MESSAGE_TURTLESRVREQUEST_H
